on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: dart-test-2022/string_indexing_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - name: Run tests
        run: dart test --file-reporter json:tests.json
